# Generated by Django 5.0.14 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0016_citationcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='school_level',
            field=models.CharField(blank=True, db_column='user_school_level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='school_name',
            field=models.CharField(blank=True, db_column='user_school_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='client_type',
            field=models.CharField(blank=True, db_column='user_client_type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sex',
            field=models.CharField(blank=True, db_column='user_sex', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='age',
            field=models.CharField(blank=True, db_column='user_age', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='region',
            field=models.CharField(blank=True, db_column='user_region', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='category',
            field=models.CharField(blank=True, db_column='user_category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='terms_accepted',
            field=models.BooleanField(db_column='user_terms_accepted', default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, db_column='user_terms_accepted_at', null=True),
        ),
    ]
