# Generated by Django 5.0.14 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0017_useraccount_profile_fields_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='terms_version',
            field=models.CharField(blank=True, db_column='user_terms_version', max_length=50, null=True),
        ),
    ]
