# Generated by Django 5.0.14 on 2026-04-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0018_useraccount_terms_version'),
    ]

    operations = [
    ]
