# Generated by Django 5.0.14 on 2026-04-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0020_update_general_to_irrelevant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('ai_model_settings', models.JSONField(default=dict)),
                ('search_settings', models.JSONField(default=dict)),
                ('api_integrations', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
