# Generated by Django 5.0.14 on 2026-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0021_alter_csmfeedback_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='api_integrations',
            new_name='environment_config',
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='category',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('DOST Employee', 'DOST Employee'), ('Other Government Employee', 'Other Government Employee'), ('Librarian/Library Staff', 'Librarian/Library Staff'), ('Teaching Personnel', 'Teaching Personnel'), ('Administrative Personnel', 'Administrative Personnel'), ('Researcher', 'Researcher')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='client_type',
            field=models.CharField(choices=[('Student', 'Student'), ('DOST Employee', 'DOST Employee'), ('Other Government Employee', 'Other Government Employee'), ('Librarian/Library Staff', 'Librarian/Library Staff'), ('Teaching Personnel', 'Teaching Personnel'), ('Administrative Personnel', 'Administrative Personnel'), ('Researcher', 'Researcher')], max_length=50),
        ),
    ]
