# Generated by Django 5.0.14 on 2026-04-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0022_rename_api_integrations_systemsettings_environment_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStructureRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('schema_version', models.CharField(max_length=50)),
                ('migration_label', models.CharField(blank=True, max_length=120, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('rollback_script', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_structures_created', to='rag_api.useraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_structures_updated', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'database_structure_records',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackupRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('schema', 'Schema only')], default='full', max_length=20)),
                ('target_environment', models.CharField(blank=True, max_length=60, null=True)),
                ('storage_location', models.CharField(max_length=255)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('backup_started_at', models.DateTimeField(blank=True, null=True)),
                ('backup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_backups_created', to='rag_api.useraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_backups_updated', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'database_backup_records',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
