# Generated by Django 5.0.14 on 2026-04-29 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0023_databasestructurerecord_databasebackuprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAccessControlRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('subject_type', models.CharField(choices=[('role', 'Role'), ('user', 'User'), ('group', 'Group')], default='role', max_length=20)),
                ('subject_name', models.CharField(max_length=150)),
                ('resource_name', models.CharField(max_length=150)),
                ('permission_level', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=20)),
                ('scope', models.CharField(blank=True, max_length=120, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_access_rules_created', to='rag_api.useraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_access_rules_updated', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'security_access_control_rules',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('role_change', 'Role change'), ('access_change', 'Access change'), ('security_update', 'Security update'), ('manual_note', 'Manual note')], default='manual_note', max_length=30)),
                ('actor_label', models.CharField(max_length=150)),
                ('target_label', models.CharField(blank=True, max_length=150, null=True)),
                ('action_summary', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('blocked', 'Blocked'), ('failure', 'Failure')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs_created', to='rag_api.useraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs_updated', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'security_audit_log_entries',
                'ordering': ['-occurred_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuthenticationPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('authentication_mode', models.CharField(choices=[('password', 'Password only'), ('password_mfa', 'Password + MFA'), ('sso', 'Single sign-on'), ('hybrid', 'Hybrid')], default='password_mfa', max_length=30)),
                ('password_min_length', models.PositiveSmallIntegerField(default=12)),
                ('password_history_count', models.PositiveSmallIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('max_failed_attempts', models.PositiveSmallIntegerField(default=5)),
                ('lockout_minutes', models.PositiveIntegerField(default=15)),
                ('require_mfa', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_auth_policies_created', to='rag_api.useraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_auth_policies_updated', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'security_authentication_policies',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
