# Generated by Django 5.0.14 on 2026-04-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0024_securityaccesscontrolrule_securityauditlogentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmfeedback',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_csm_feedback', to='rag_api.useraccount'),
        ),
    ]