# Generated by Django 5.0.14 on 2026-05-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0025_csmfeedback_edit_audit_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmfeedback',
            name='company',
            field=models.CharField(blank=True, help_text='For Citizen client type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='school_level',
            field=models.CharField(blank=True, help_text='For Student client type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='school_name',
            field=models.CharField(blank=True, help_text='For Student client type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='client_type',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Student', 'Student'), ('DOST Employee', 'DOST Employee'), ('Other Government Employee', 'Other Government Employee'), ('Librarian/Library Staff', 'Librarian/Library Staff'), ('Teaching Personnel', 'Teaching Personnel'), ('Administrative Personnel', 'Administrative Personnel'), ('Researcher', 'Researcher')], max_length=50),
        ),
    ]
