# Generated by Django 5.0.14 on 2026-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0026_csmfeedback_company_csmfeedback_school_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmfeedback',
            name='region',
            field=models.CharField(choices=[('NCR', '[NCR] National Capital Region'), ('CAR', '[CAR] Cordillera Administrative Region'), ('R01', '[R01] Region 1 (Ilocos Region)'), ('R02', '[R02] Region 2 (Cagayan Valley Region)'), ('R03', '[R03] Region 3 (Central Luzon Region)'), ('R4A', '[R4A] Region 4A (CALABARZON Region)'), ('R4B', '[R4B] Region 4B (MIMAROPA Region)'), ('R05', '[R05] Region 5 (Bicol Region)'), ('R06', '[R06] Western Visayas Region'), ('R07', '[R07] Central Visayas Region'), ('R08', '[R08] Eastern Visayas Region'), ('R09', '[R09] Zamboanga Peninsula Region'), ('R10', '[R10] Northern Mindanao Region'), ('R11', '[R11] Davao Region'), ('R12', '[R12] SOCCSKSARGEN Region'), ('R13', '[R13] Caraga Administrative Region'), ('R18', '[R18] Negros Island Region (NIR)'), ('BARMM', '[BARMM] Bangsamoro Autonomous Region in Muslim Mindanao'), ('N/A', '[N/A] Not Applicable (Overseas)')], max_length=50),
        ),
    ]
